/**
 * pdfReport.js — UPGRADED Government PDF Report
 * MeitY Official Style — Ashoka Emblem + Tricolor + Risk Gauge + Entity Cards
 */

export async function generatePIIReport(result, user) {
  const { jsPDF } = await import('jspdf')

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const W = 210
  const margin = 14
  let y = 0

  // ── Color Palette ──────────────────────────────────────────────────────────
  const govBlue    = [0, 40, 104]
  const govBlue2   = [0, 53, 128]
  const govGold    = [198, 160, 60]
  const saffron    = [255, 153, 51]
  const indGreen   = [19, 136, 8]
  const white      = [255, 255, 255]
  const lightBlue  = [235, 242, 255]
  const darkGray   = [30, 30, 40]
  const midGray    = [100, 100, 110]
  const lightGray  = [245, 246, 250]
  const red        = [192, 30, 30]
  const orange     = [210, 100, 15]
  const amber      = [180, 130, 0]
  const green      = [20, 130, 20]

  // ── Helpers ────────────────────────────────────────────────────────────────
  const fillRect = (x, yw, ww, hh, color) => {
    doc.setFillColor(...color); doc.rect(x, yw, ww, hh, 'F')
  }
  const strokeRect = (x, yw, ww, hh, color, lw = 0.3) => {
    doc.setDrawColor(...color); doc.setLineWidth(lw); doc.rect(x, yw, ww, hh, 'S')
  }
  const txt = (t, x, yw, opts = {}) => doc.text(String(t), x, yw, opts)
  const setF = (size, style = 'normal', color = darkGray) => {
    doc.setFontSize(size); doc.setFont('helvetica', style); doc.setTextColor(...color)
  }
  const hline = (x1, yw, x2, color = [200,200,210], lw = 0.3) => {
    doc.setDrawColor(...color); doc.setLineWidth(lw); doc.line(x1, yw, x2, yw)
  }
  const riskColor = (lvl) => ({
    CRITICAL: red, HIGH: orange, MEDIUM: amber, LOW: green
  }[lvl] || midGray)

  const riskBg = (lvl) => ({
    CRITICAL: [255,235,235], HIGH: [255,243,230],
    MEDIUM:   [255,250,220], LOW:  [230,255,230]
  }[lvl] || lightGray)

  // ── PAGE BACKGROUND ────────────────────────────────────────────────────────
  fillRect(0, 0, W, 297, white)

  // ── TRICOLOR TOP STRIPE ────────────────────────────────────────────────────
  fillRect(0, 0, W, 3, saffron)
  fillRect(0, 3, W, 3, white)
  fillRect(0, 6, W, 3, indGreen)
  y = 9

  // ── MAIN HEADER ────────────────────────────────────────────────────────────
  fillRect(0, y, W, 42, govBlue)

  // Gold left accent line
  fillRect(margin - 2, y + 4, 2, 34, govGold)

  // Ashoka Chakra
  const cx = margin + 10, cy = y + 21, r = 9
  doc.setFillColor(...govGold)
  doc.circle(cx, cy, r, 'S')
  doc.setDrawColor(...govGold)
  doc.setLineWidth(0.5)
  doc.circle(cx, cy, r, 'S')
  doc.circle(cx, cy, r * 0.65, 'S')
  doc.circle(cx, cy, 1.2, 'F')
  for (let i = 0; i < 24; i++) {
    const angle = (i * 15 * Math.PI) / 180
    const x1 = cx + Math.cos(angle) * 2
    const y1 = cy + Math.sin(angle) * 2
    const x2 = cx + Math.cos(angle) * r * 0.95
    const y2 = cy + Math.sin(angle) * r * 0.95
    doc.setLineWidth(0.2)
    doc.line(x1, y1, x2, y2)
  }

  // Header text — ← FIXED: Hindi removed, English only
  setF(6.5, 'normal', [200, 215, 255])
  txt('GOVERNMENT OF INDIA  |  BHARATH SARKAR', margin + 24, y + 10)

  setF(11.5, 'bold', white)
  txt('Ministry of Electronics & Information Technology (MeitY)', margin + 24, y + 20)

  setF(8.5, 'bold', [180, 210, 255])
  txt('Intelligent PII Detection & Risk Assessment System', margin + 24, y + 29)

  setF(6.5, 'normal', [140, 175, 230])
  txt('OFFICIAL REPORT  —  RESTRICTED', margin + 24, y + 37)

  // RESTRICTED badge
  fillRect(W - 52, y + 7, 40, 11, [160, 15, 15])
  doc.setDrawColor(...govGold)
  doc.setLineWidth(0.4)
  doc.rect(W - 52, y + 7, 40, 11, 'S')
  setF(7.5, 'bold', white)
  txt('** RESTRICTED **', W - 32, y + 15, { align: 'center' })

  // Report ID
  setF(5.5, 'normal', [150, 185, 235])
  txt(`Report ID: ${result.request_id || 'RPT-' + Date.now()}`, W - margin, y + 38, { align: 'right' })

  // Gold divider
  fillRect(0, y + 42, W, 1.5, govGold)
  y += 45

  // ── META INFO ROW ──────────────────────────────────────────────────────────
  fillRect(0, y, W, 18, lightBlue)
  hline(0, y, W, [190, 210, 240], 0.4)
  hline(0, y + 18, W, [190, 210, 240], 0.4)

  const now = new Date()
  const metaItems = [
    ['GENERATED BY', `${user?.name || 'Admin User'}\n(${user?.role || 'SYSTEM_ADMIN'})`],
    ['EMPLOYEE ID',  user?.employeeId || '—'],
    ['DATE & TIME',  now.toLocaleString('en-IN', { dateStyle: 'long', timeStyle: 'medium' })],
    ['CLEARANCE',    user?.clearance || '—'],
  ]
  const mW = (W - margin * 2) / metaItems.length
  metaItems.forEach(([label, val], i) => {
    const mx = margin + i * mW
    if (i > 0) { doc.setDrawColor(190, 210, 240); doc.setLineWidth(0.3); doc.line(mx, y + 3, mx, y + 15) }
    setF(5.5, 'bold', midGray); txt(label, mx + 3, y + 7)
    setF(6.5, 'bold', govBlue); txt(val.split('\n')[0], mx + 3, y + 13)
    if (val.includes('\n')) { setF(5.5, 'normal', midGray); txt(val.split('\n')[1], mx + 3, y + 17) }
  })
  y += 22

  // ── RISK SUMMARY CARD ──────────────────────────────────────────────────────
  const risk = result.risk_summary || {}
  const riskLevel = risk.overall_risk || 'LOW'
  const rCol = riskColor(riskLevel)
  const rBg  = riskBg(riskLevel)

  fillRect(margin, y, W - margin * 2, 32, rBg)
  fillRect(margin, y, 4, 32, rCol)
  strokeRect(margin, y, W - margin * 2, 32, rCol, 0.5)

  setF(8, 'bold', govBlue); txt('DETECTION SUMMARY', margin + 8, y + 8)
  setF(7, 'normal', midGray); txt(`Risk Score: ${risk.risk_score ?? '—'}`, margin + 8, y + 15)
  setF(6.5, 'normal', darkGray)
  const recLines = doc.splitTextToSize(risk.recommendation || 'No recommendation.', 110)
  recLines.slice(0, 2).forEach((l, i) => txt(l, margin + 8, y + 21 + i * 5))

  // Risk badge right side
  fillRect(W - margin - 50, y + 4, 47, 24, rCol)
  setF(13, 'bold', white); txt(riskLevel, W - margin - 26.5, y + 16, { align: 'center' })
  setF(6.5, 'bold', white); txt(`${risk.total_entities ?? 0} Entities Found`, W - margin - 26.5, y + 23, { align: 'center' })
  y += 37

  // ── RISK GAUGE VISUAL ──────────────────────────────────────────────────────
  setF(6.5, 'bold', govBlue); txt('RISK GAUGE', margin, y + 5)
  const gaugeX = margin + 28, gaugeW = W - margin * 2 - 30, gaugeH = 6
  const segments = [
    { color: [80,180,80],   w: 0.25 },
    { color: [220,180,30],  w: 0.25 },
    { color: [220,100,20],  w: 0.25 },
    { color: [190,30,30],   w: 0.25 },
  ]
  let sx = gaugeX
  segments.forEach(({ color, w }) => {
    fillRect(sx, y, gaugeW * w, gaugeH, color)
    sx += gaugeW * w
  })
  const scoreRatio = Math.min((risk.risk_score ?? 0) / 100, 1)
  const needleX = gaugeX + gaugeW * scoreRatio
  doc.setDrawColor(20, 20, 20); doc.setLineWidth(1)
  doc.line(needleX, y - 1, needleX, y + gaugeH + 1)
  fillRect(needleX - 1.5, y - 3, 3, 3, darkGray)
  setF(6, 'bold', darkGray); txt(`${risk.risk_score ?? 0}`, needleX, y - 4, { align: 'center' })
  setF(5, 'normal', midGray)
  txt('0', gaugeX, y + gaugeH + 4)
  txt('25', gaugeX + gaugeW * 0.25, y + gaugeH + 4, { align: 'center' })
  txt('50', gaugeX + gaugeW * 0.50, y + gaugeH + 4, { align: 'center' })
  txt('75', gaugeX + gaugeW * 0.75, y + gaugeH + 4, { align: 'center' })
  txt('100', gaugeX + gaugeW, y + gaugeH + 4, { align: 'right' })
  y += gaugeH + 10

  // ── BREAKDOWN STAT CARDS ───────────────────────────────────────────────────
  const breakdown = [
    { label: 'CRITICAL', count: risk.critical_count ?? 0, color: red,    bg: [255,235,235] },
    { label: 'HIGH',     count: risk.high_count     ?? 0, color: orange, bg: [255,243,228] },
    { label: 'MEDIUM',   count: risk.medium_count   ?? 0, color: amber,  bg: [255,251,220] },
    { label: 'LOW',      count: risk.low_count      ?? 0, color: green,  bg: [228,255,228] },
  ]
  const bW = (W - margin * 2 - 9) / 4
  breakdown.forEach(({ label, count, color, bg }, i) => {
    const bx = margin + i * (bW + 3)
    fillRect(bx, y, bW, 18, bg)
    fillRect(bx, y, bW, 2, color)
    strokeRect(bx, y, bW, 18, color, 0.3)
    setF(14, 'bold', color); txt(String(count), bx + bW / 2, y + 12, { align: 'center' })
    setF(5.5, 'bold', color); txt(label, bx + bW / 2, y + 17, { align: 'center' })
  })
  y += 24

  // ── AI PIPELINE BANNER ─────────────────────────────────────────────────────
  fillRect(margin, y, W - margin * 2, 11, govBlue2)
  setF(6.5, 'bold', white)
  const layers = result.ai_layers_used || ['REGEX']
  const layerStr = layers.map(l =>
    l === 'BERT' ? 'BERT Transformer' : l === 'spaCy' ? 'spaCy NER' : 'Regex Engine'
  ).join('  ->  ')
  txt(`AI PIPELINE:  ${layerStr}`, margin + 4, y + 7)
  if (result.processing_time_ms) {
    setF(6, 'normal', [170, 200, 240])
    txt(`${result.processing_time_ms.toFixed(1)} ms`, W - margin - 2, y + 7, { align: 'right' })
  }
  y += 15

  // ── ENTITIES TABLE ─────────────────────────────────────────────────────────
  setF(8, 'bold', govBlue)
  txt('DETECTED PII ENTITIES', margin, y)
  hline(margin, y + 1, W - margin, govGold, 0.8)
  y += 6

  const entities = result.entities || []

  if (entities.length === 0) {
    fillRect(margin, y, W - margin * 2, 14, [228, 255, 228])
    strokeRect(margin, y, W - margin * 2, 14, green, 0.4)
    setF(9, 'bold', green); txt('No PII Detected — Document is Safe', W / 2, y + 9, { align: 'center' })
    y += 18
  } else {
    const cols = [
      { label: '#',            w: 8  },
      { label: 'PII TYPE',     w: 42 },
      { label: 'MASKED VALUE', w: 52 },
      { label: 'RISK',         w: 20 },
      { label: 'CONF.',        w: 18 },
      { label: 'SOURCE',       w: 28 },
    ]
    fillRect(margin, y, W - margin * 2, 8, govBlue)
    let cx = margin + 2
    cols.forEach(({ label, w }) => {
      setF(6, 'bold', white); txt(label, cx, y + 5.5)
      cx += w
    })
    y += 8

    entities.forEach((ent, idx) => {
      const rowBg = idx % 2 === 0 ? [248,249,255] : white
      fillRect(margin, y, W - margin * 2, 8, rowBg)
      const rC = riskColor(ent.risk_level)
      fillRect(margin, y, 2, 8, rC)

      const rowData = [
        String(idx + 1),
        ent.type?.replace(/_/g, ' ') || '—',
        ent.masked_value || ent.value || '—',
        ent.risk_level || '—',
        ent.confidence ? `${(ent.confidence * 100).toFixed(0)}%` : '—',
        ent.source || '—',
      ]
      cx = margin + 2
      cols.forEach(({ w }, ci) => {
        const cellColor = ci === 3 ? rC : (ci === 4 ? govBlue : darkGray)
        const fontStyle = (ci === 3 || ci === 4) ? 'bold' : 'normal'
        setF(6.5, fontStyle, cellColor)
        const cellText = String(rowData[ci])
        txt(cellText.length > 24 ? cellText.slice(0, 21) + '...' : cellText, cx, y + 5.5)
        cx += w
      })
      hline(margin, y + 8, W - margin, [215, 220, 235], 0.2)
      y += 8

      if (y > 262) {
        doc.addPage()
        fillRect(0, 0, W, 3, saffron)
        fillRect(0, 3, W, 3, white)
        fillRect(0, 6, W, 3, indGreen)
        fillRect(0, 9, W, 10, govBlue)
        setF(6, 'normal', [200, 215, 255]); txt('MeitY — PII Detection Report (continued)', margin, 16)
        setF(5.5, 'normal', [150, 185, 235]); txt(`Report ID: ${result.request_id}`, W - margin, 16, { align: 'right' })
        y = 24
      }
    })
  }
  y += 4

  // ── MASKED TEXT SECTION ────────────────────────────────────────────────────
  const textToShow = result.original_text || result.transcript || ''
  if (textToShow) {
    if (y > 230) { doc.addPage(); y = 14 }
    setF(8, 'bold', govBlue); txt('ANALYSED TEXT (MASKED)', margin, y)
    hline(margin, y + 1, W - margin, govGold, 0.6)
    y += 5

    const maskedText = result.masked_text || textToShow
    const lines = doc.splitTextToSize(maskedText, W - margin * 2 - 8)
    const maxL = Math.min(lines.length, 18)
    const boxH = maxL * 4.5 + 6
    fillRect(margin, y, W - margin * 2, boxH, [252, 250, 242])
    strokeRect(margin, y, W - margin * 2, boxH, [200, 190, 160], 0.3)
    fillRect(margin, y, W - margin * 2, 1.5, govGold)
    setF(6.5, 'normal', darkGray)
    lines.slice(0, maxL).forEach((l, i) => txt(l, margin + 4, y + 5 + i * 4.5))
    if (lines.length > maxL) {
      setF(5.5, 'normal', midGray)
      txt(`[+ ${lines.length - maxL} more lines]`, margin + 4, y + 5 + maxL * 4.5)
    }
    y += boxH + 8
  }

  // ── LEGAL DISCLAIMER ───────────────────────────────────────────────────────
  if (y > 255) { doc.addPage(); y = 14 }
  hline(margin, y, W - margin, govGold, 0.8)
  y += 4
  fillRect(margin, y, W - margin * 2, 24, [255, 250, 225])
  strokeRect(margin, y, W - margin * 2, 24, [180, 140, 30], 0.3)
  fillRect(margin, y, 3, 24, [180, 140, 30])
  setF(6.5, 'bold', [100, 70, 0]); txt('LEGAL DISCLAIMER', margin + 6, y + 7)
  setF(5.5, 'normal', [100, 70, 0])
  const disclaimer = 'This report is generated by an AI-powered system for official use only. Classified as RESTRICTED under Government of India data classification policy. Unauthorized disclosure is prohibited under Section 66 of the IT Act 2000. All PII data shown has been masked to protect data subject privacy as required under the Digital Personal Data Protection Act 2023.'
  const dLines = doc.splitTextToSize(disclaimer, W - margin * 2 - 10)
  dLines.slice(0, 3).forEach((l, i) => txt(l, margin + 6, y + 13 + i * 4))
  y += 28

  // ── FOOTER ─────────────────────────────────────────────────────────────────
  const footerY = 285
  fillRect(0, footerY, W, 8, govBlue)
  fillRect(0, footerY - 1.5, W, 1.5, govGold)
  setF(5.5, 'normal', [170, 195, 235])
  txt(
    '© 2024 Ministry of Electronics & Information Technology, Government of India  |  IT Act 2000  .  DPDP Act 2023  .  NIC Infrastructure',
    W / 2, footerY + 5, { align: 'center' }
  )

  // Tricolor bottom stripe
  fillRect(0, 293, W, 1.3, saffron)
  fillRect(0, 294.3, W, 1.3, white)
  fillRect(0, 295.6, W, 1.3, indGreen)

  // ── SAVE ───────────────────────────────────────────────────────────────────
  const fileName = `PII_Report_${result.request_id || Date.now()}_${now.toISOString().slice(0,10)}.pdf`
  doc.save(fileName)
}